---
name: Math-Vec
version: 0.04
author: []
abstract: Object-Oriented Vector Math Methods in Perl
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
provides:
  Math::Vec:
    file: lib/Math/Vec.pm
    version: 0.04
generated_by: Module::Build version 0.28
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
